import type { CSSProperties } from "react";

/**
 * Snapshot workspace chrome styles.
 *
 * The solid chrome (sidebar, right panel, section headers, module/commit rows,
 * inspector) uses fh design tokens so it reads correctly in both themes.
 *
 * The floating HUD overlays over the 3D viewport (diff view segment, diff
 * toggle, changes overlay) keep a fixed dark-glass surface. They sit on top of
 * the r3f canvas — which has its own dark background in both themes — so, like
 * the app header, they are intentionally theme-independent. See apps/web/DESIGN.md.
 */
export const gltfSceneWorkspaceStyles: Record<string, CSSProperties> = {
  sidebar: {
    width: 240,
    borderRight: "1px solid rgb(var(--fh-border))",
    backgroundColor: "rgb(var(--fh-surface))",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  sideSection: { borderBottom: "1px solid rgb(var(--fh-border-muted))", padding: "10px 0" },
  sideSectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 12px 6px",
    fontSize: 11,
    fontWeight: 600,
    color: "rgb(var(--fh-fg-muted))",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  muted: { fontSize: 12, color: "rgb(var(--fh-fg-subtle))", margin: 0 },

  moduleBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "6px 12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    borderRadius: 0,
  },
  moduleBtnSelected: { backgroundColor: "rgb(var(--fh-accent-muted))" },
  moduleIcon: { fontSize: 13, color: "rgb(var(--fh-fg-subtle))", flexShrink: 0 },
  moduleName: {
    fontSize: 13,
    color: "rgb(var(--fh-fg))",
    fontWeight: 500,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  moduleCommitCount: { fontSize: 11, color: "rgb(var(--fh-fg-subtle))", flexShrink: 0 },

  viewport: { flex: 1, overflow: "hidden", position: "relative" },

  // ── Floating HUD over the 3D canvas — theme-independent dark glass ──
  diffViewSegment: {
    position: "absolute",
    top: 12,
    right: 200,
    zIndex: 10,
    display: "flex",
    gap: 0,
    borderRadius: 6,
    overflow: "hidden",
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(15,23,42,0.75)",
    backdropFilter: "blur(4px)",
  },
  diffViewBtn: {
    fontSize: 11,
    fontWeight: 600,
    color: "#94a3b8",
    background: "transparent",
    border: "none",
    padding: "5px 10px",
    cursor: "pointer",
    lineHeight: 1,
  },
  diffViewBtnActive: {
    color: "#f8fafc",
    background: "rgba(255,255,255,0.12)",
  },
  diffToggle: {
    position: "absolute",
    top: 12,
    right: 88,
    zIndex: 10,
    fontSize: 12,
    fontWeight: 600,
    color: "#e2e8f0",
    background: "rgba(15,23,42,0.75)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 6,
    padding: "4px 10px",
    cursor: "pointer",
    backdropFilter: "blur(4px)",
  },
  changesOverlay: {
    position: "absolute",
    bottom: 28,
    left: 12,
    zIndex: 10,
    background: "rgba(15,23,42,0.85)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 8,
    minWidth: 200,
    maxWidth: 260,
    maxHeight: 260,
    overflowY: "auto",
    backdropFilter: "blur(6px)",
  },
  overlayHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 10px",
    fontSize: 10,
    fontWeight: 700,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  overlayRow: { display: "flex", alignItems: "center", gap: 6, padding: "4px 10px", cursor: "pointer" },
  overlayRowSelected: { backgroundColor: "rgba(255,255,255,0.08)" },
  overlayName: {
    fontSize: 12,
    color: "#e2e8f0",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  overlayKind: { fontSize: 10, color: "#64748b", flexShrink: 0 },
  // ── end HUD ──

  viewportPlaceholder: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    color: "rgb(var(--fh-fg-subtle))",
  },
  viewportIcon: { fontSize: 64, display: "block", marginBottom: 12 },
  viewportText: { fontSize: 18, fontWeight: 600, color: "rgb(var(--fh-fg-muted))", margin: 0 },
  viewportSub: { fontSize: 13, color: "rgb(var(--fh-fg-subtle))", marginTop: 6 },

  rightPanel: {
    width: 300,
    borderLeft: "1px solid rgb(var(--fh-border))",
    backgroundColor: "rgb(var(--fh-surface))",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },

  commitsSection: { borderBottom: "1px solid rgb(var(--fh-border-muted))", overflowY: "auto", maxHeight: 280, flexShrink: 0 },
  commitBtn: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    padding: "6px 12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  },
  commitBtnActive: { backgroundColor: "rgb(var(--fh-accent-muted))" },
  commitTrack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 4,
    flexShrink: 0,
    width: 12,
  },
  commitDot: { width: 8, height: 8, borderRadius: "50%", backgroundColor: "rgb(var(--fh-border-strong))", flexShrink: 0 },
  commitDotActive: { backgroundColor: "rgb(var(--fh-accent-emphasis))" },
  commitLine: { width: 2, flex: 1, backgroundColor: "rgb(var(--fh-border))", minHeight: 8, marginTop: 2 },
  commitInfo: { display: "flex", flexDirection: "column", gap: 2, flex: 1, minWidth: 0 },
  commitMsg: {
    fontSize: 12,
    color: "rgb(var(--fh-fg))",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  commitDate: { fontSize: 10, color: "rgb(var(--fh-fg-subtle))" },
  commitSha: {
    fontSize: 10,
    color: "rgb(var(--fh-fg-subtle))",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    background: "rgb(var(--fh-surface-muted))",
    borderRadius: 3,
    padding: "0 3px",
  },
  commitDiffBadges: { display: "flex", gap: 4, marginTop: 2 },

  rightPlaceholder: { fontSize: 12, color: "rgb(var(--fh-fg-subtle))", padding: "12px", flex: 1 },
  paramKey: { fontSize: 11, color: "rgb(var(--fh-fg-subtle))", textTransform: "uppercase", letterSpacing: "0.04em" },
  paramValue: {
    fontSize: 12,
    color: "rgb(var(--fh-fg))",
    wordBreak: "break-word",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
};
