import type { CSSProperties } from "react";

export const gltfSceneWorkspaceStyles: Record<string, CSSProperties> = {
  sidebar: { width: 240, borderRight: "1px solid #e5e7eb", backgroundColor: "#fff", display: "flex", flexDirection: "column", overflow: "hidden" },
  sideSection: { borderBottom: "1px solid #f3f4f6", padding: "10px 0" },
  sideSectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 12px 6px",
    fontSize: 11,
    fontWeight: 600,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  muted: { fontSize: 12, color: "#9ca3af", margin: 0 },

  moduleBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "6px 12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    borderRadius: 0,
  },
  moduleBtnSelected: { backgroundColor: "#f0f9ff" },
  moduleIcon: { fontSize: 13, color: "#6b7280", flexShrink: 0 },
  moduleName: {
    fontSize: 13,
    color: "#111827",
    fontWeight: 500,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  moduleCommitCount: { fontSize: 11, color: "#9ca3af", flexShrink: 0 },

  viewport: { flex: 1, overflow: "hidden", position: "relative" },
  diffViewSegment: {
    position: "absolute",
    top: 12,
    right: 200,
    zIndex: 10,
    display: "flex",
    gap: 0,
    borderRadius: 6,
    overflow: "hidden",
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(15,23,42,0.75)",
    backdropFilter: "blur(4px)",
  },
  diffViewBtn: {
    fontSize: 11,
    fontWeight: 600,
    color: "#94a3b8",
    background: "transparent",
    border: "none",
    padding: "5px 10px",
    cursor: "pointer",
    lineHeight: 1,
  },
  diffViewBtnActive: {
    color: "#f8fafc",
    background: "rgba(255,255,255,0.12)",
  },
  diffToggle: {
    position: "absolute",
    top: 12,
    right: 88,
    zIndex: 10,
    fontSize: 12,
    fontWeight: 600,
    color: "#e2e8f0",
    background: "rgba(15,23,42,0.75)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 6,
    padding: "4px 10px",
    cursor: "pointer",
    backdropFilter: "blur(4px)",
  },
  changesOverlay: {
    position: "absolute",
    bottom: 28,
    left: 12,
    zIndex: 10,
    background: "rgba(15,23,42,0.85)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 8,
    minWidth: 200,
    maxWidth: 260,
    maxHeight: 260,
    overflowY: "auto",
    backdropFilter: "blur(6px)",
  },
  overlayHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 10px",
    fontSize: 10,
    fontWeight: 700,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  overlayRow: { display: "flex", alignItems: "center", gap: 6, padding: "4px 10px", cursor: "pointer" },
  overlayRowSelected: { backgroundColor: "rgba(255,255,255,0.08)" },
  overlayName: {
    fontSize: 12,
    color: "#e2e8f0",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  overlayKind: { fontSize: 10, color: "#64748b", flexShrink: 0 },
  viewportPlaceholder: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    color: "#9ca3af",
  },
  viewportIcon: { fontSize: 64, display: "block", marginBottom: 12 },
  viewportText: { fontSize: 18, fontWeight: 600, color: "#6b7280", margin: 0 },
  viewportSub: { fontSize: 13, color: "#9ca3af", marginTop: 6 },

  rightPanel: {
    width: 300,
    borderLeft: "1px solid #e5e7eb",
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },

  commitsSection: { borderBottom: "1px solid #f3f4f6", overflowY: "auto", maxHeight: 280, flexShrink: 0 },
  commitBtn: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    padding: "6px 12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  },
  commitBtnActive: { backgroundColor: "#f0f9ff" },
  commitTrack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 4,
    flexShrink: 0,
    width: 12,
  },
  commitDot: { width: 8, height: 8, borderRadius: "50%", backgroundColor: "#cbd5e1", flexShrink: 0 },
  commitDotActive: { backgroundColor: "#3b82f6" },
  commitLine: { width: 2, flex: 1, backgroundColor: "#e5e7eb", minHeight: 8, marginTop: 2 },
  commitInfo: { display: "flex", flexDirection: "column", gap: 2, flex: 1, minWidth: 0 },
  commitMsg: {
    fontSize: 12,
    color: "#111827",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  commitDate: { fontSize: 10, color: "#9ca3af" },
  commitSha: {
    fontSize: 10,
    color: "#94a3b8",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    background: "#f1f5f9",
    borderRadius: 3,
    padding: "0 3px",
  },
  commitDiffBadges: { display: "flex", gap: 4, marginTop: 2 },

  rightPlaceholder: { fontSize: 12, color: "#9ca3af", padding: "12px", flex: 1 },
  paramKey: { fontSize: 11, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.04em" },
  paramValue: {
    fontSize: 12,
    color: "#0f172a",
    wordBreak: "break-word",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
};
